// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/privateKey.proto
// Protobuf Java Version: 4.29.3

package org.parsa.grpcservicenode.privateKey;

public final class PrivateKey {
  private PrivateKey() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PrivateKey.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_privatekey_PrivateKeyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_privatekey_PrivateKeyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_privatekey_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_privatekey_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>src/main/java/org/parsa/grpcservicenod" +
      "e/proto/privateKey.proto\022\nprivatekey\"(\n\021" +
      "PrivateKeyMessage\022\023\n\013private_key\030\001 \001(\t\"\026" +
      "\n\003Ack\022\017\n\007success\030\001 \001(\0102X\n\021PrivateKeyServ" +
      "ice\022C\n\021ReceivePrivateKey\022\035.privatekey.Pr" +
      "ivateKeyMessage\032\017.privatekey.AckB(\n$org." +
      "parsa.grpcservicenode.privateKeyP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_privatekey_PrivateKeyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_privatekey_PrivateKeyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_privatekey_PrivateKeyMessage_descriptor,
        new java.lang.String[] { "PrivateKey", });
    internal_static_privatekey_Ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_privatekey_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_privatekey_Ack_descriptor,
        new java.lang.String[] { "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
