// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: CoreBasedGoLang/consensus/consensus.proto

package consensus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreConsensusService_ReportLeader_FullMethodName   = "/consensus.CoreConsensusService/ReportLeader"
	CoreConsensusService_SendPrivateKey_FullMethodName = "/consensus.CoreConsensusService/SendPrivateKey"
	CoreConsensusService_ReportVote_FullMethodName     = "/consensus.CoreConsensusService/ReportVote"
)

// CoreConsensusServiceClient is the client API for CoreConsensusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreConsensusServiceClient interface {
	ReportLeader(ctx context.Context, in *LeaderMessage, opts ...grpc.CallOption) (*Ack, error)
	SendPrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error)
	ReportVote(ctx context.Context, in *VoteReport, opts ...grpc.CallOption) (*Ack, error)
}

type coreConsensusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreConsensusServiceClient(cc grpc.ClientConnInterface) CoreConsensusServiceClient {
	return &coreConsensusServiceClient{cc}
}

func (c *coreConsensusServiceClient) ReportLeader(ctx context.Context, in *LeaderMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreConsensusService_ReportLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreConsensusServiceClient) SendPrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivateKeyResponse)
	err := c.cc.Invoke(ctx, CoreConsensusService_SendPrivateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreConsensusServiceClient) ReportVote(ctx context.Context, in *VoteReport, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreConsensusService_ReportVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreConsensusServiceServer is the server API for CoreConsensusService service.
// All implementations must embed UnimplementedCoreConsensusServiceServer
// for forward compatibility.
type CoreConsensusServiceServer interface {
	ReportLeader(context.Context, *LeaderMessage) (*Ack, error)
	SendPrivateKey(context.Context, *PrivateKeyRequest) (*PrivateKeyResponse, error)
	ReportVote(context.Context, *VoteReport) (*Ack, error)
	mustEmbedUnimplementedCoreConsensusServiceServer()
}

// UnimplementedCoreConsensusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreConsensusServiceServer struct{}

func (UnimplementedCoreConsensusServiceServer) ReportLeader(context.Context, *LeaderMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportLeader not implemented")
}
func (UnimplementedCoreConsensusServiceServer) SendPrivateKey(context.Context, *PrivateKeyRequest) (*PrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrivateKey not implemented")
}
func (UnimplementedCoreConsensusServiceServer) ReportVote(context.Context, *VoteReport) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportVote not implemented")
}
func (UnimplementedCoreConsensusServiceServer) mustEmbedUnimplementedCoreConsensusServiceServer() {}
func (UnimplementedCoreConsensusServiceServer) testEmbeddedByValue()                              {}

// UnsafeCoreConsensusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreConsensusServiceServer will
// result in compilation errors.
type UnsafeCoreConsensusServiceServer interface {
	mustEmbedUnimplementedCoreConsensusServiceServer()
}

func RegisterCoreConsensusServiceServer(s grpc.ServiceRegistrar, srv CoreConsensusServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreConsensusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreConsensusService_ServiceDesc, srv)
}

func _CoreConsensusService_ReportLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreConsensusServiceServer).ReportLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreConsensusService_ReportLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreConsensusServiceServer).ReportLeader(ctx, req.(*LeaderMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreConsensusService_SendPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreConsensusServiceServer).SendPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreConsensusService_SendPrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreConsensusServiceServer).SendPrivateKey(ctx, req.(*PrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreConsensusService_ReportVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreConsensusServiceServer).ReportVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreConsensusService_ReportVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreConsensusServiceServer).ReportVote(ctx, req.(*VoteReport))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreConsensusService_ServiceDesc is the grpc.ServiceDesc for CoreConsensusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreConsensusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.CoreConsensusService",
	HandlerType: (*CoreConsensusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportLeader",
			Handler:    _CoreConsensusService_ReportLeader_Handler,
		},
		{
			MethodName: "SendPrivateKey",
			Handler:    _CoreConsensusService_SendPrivateKey_Handler,
		},
		{
			MethodName: "ReportVote",
			Handler:    _CoreConsensusService_ReportVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CoreBasedGoLang/consensus/consensus.proto",
}
