// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: CoreBasedGoLang/privateKey/privatekey.proto

package privatekey

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateKeyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKeyMessage) Reset() {
	*x = PrivateKeyMessage{}
	mi := &file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKeyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKeyMessage) ProtoMessage() {}

func (x *PrivateKeyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKeyMessage.ProtoReflect.Descriptor instead.
func (*PrivateKeyMessage) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateKeyMessage) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_CoreBasedGoLang_privateKey_privatekey_proto protoreflect.FileDescriptor

const file_CoreBasedGoLang_privateKey_privatekey_proto_rawDesc = "" +
	"\n" +
	"+CoreBasedGoLang/privateKey/privatekey.proto\x12\n" +
	"privatekey\"4\n" +
	"\x11PrivateKeyMessage\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2X\n" +
	"\x11PrivateKeyService\x12C\n" +
	"\x11ReceivePrivateKey\x12\x1d.privatekey.PrivateKeyMessage\x1a\x0f.privatekey.AckB'Z%CoreBasedGoLang/privateKey;privatekeyb\x06proto3"

var (
	file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescOnce sync.Once
	file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescData []byte
)

func file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescGZIP() []byte {
	file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescOnce.Do(func() {
		file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CoreBasedGoLang_privateKey_privatekey_proto_rawDesc), len(file_CoreBasedGoLang_privateKey_privatekey_proto_rawDesc)))
	})
	return file_CoreBasedGoLang_privateKey_privatekey_proto_rawDescData
}

var file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CoreBasedGoLang_privateKey_privatekey_proto_goTypes = []any{
	(*PrivateKeyMessage)(nil), // 0: privatekey.PrivateKeyMessage
	(*Ack)(nil),               // 1: privatekey.Ack
}
var file_CoreBasedGoLang_privateKey_privatekey_proto_depIdxs = []int32{
	0, // 0: privatekey.PrivateKeyService.ReceivePrivateKey:input_type -> privatekey.PrivateKeyMessage
	1, // 1: privatekey.PrivateKeyService.ReceivePrivateKey:output_type -> privatekey.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CoreBasedGoLang_privateKey_privatekey_proto_init() }
func file_CoreBasedGoLang_privateKey_privatekey_proto_init() {
	if File_CoreBasedGoLang_privateKey_privatekey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CoreBasedGoLang_privateKey_privatekey_proto_rawDesc), len(file_CoreBasedGoLang_privateKey_privatekey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CoreBasedGoLang_privateKey_privatekey_proto_goTypes,
		DependencyIndexes: file_CoreBasedGoLang_privateKey_privatekey_proto_depIdxs,
		MessageInfos:      file_CoreBasedGoLang_privateKey_privatekey_proto_msgTypes,
	}.Build()
	File_CoreBasedGoLang_privateKey_privatekey_proto = out.File
	file_CoreBasedGoLang_privateKey_privatekey_proto_goTypes = nil
	file_CoreBasedGoLang_privateKey_privatekey_proto_depIdxs = nil
}
