// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

public final class Node {
  private Node() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Node.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_ReadyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_ReadyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_LeaderMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_LeaderMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_VoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_node_CandidateInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_node_CandidateInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8src/main/java/org/parsa/grpcservicenod" +
      "e/proto/node.proto\022\004node\"0\n\014ReadyMessage" +
      "\022\021\n\tnode_name\030\001 \001(\t\022\r\n\005state\030\002 \001(\t\"\026\n\003Ac" +
      "k\022\017\n\007success\030\001 \001(\010\"$\n\rLeaderMessage\022\023\n\013l" +
      "eader_name\030\001 \001(\t\"M\n\013VoteRequest\022\026\n\016candi" +
      "date_name\030\001 \001(\t\022\014\n\004term\030\002 \001(\005\022\030\n\020candida" +
      "te_random\030\003 \001(\005\"2\n\014VoteResponse\022\024\n\014vote_" +
      "granted\030\001 \001(\010\022\014\n\004term\030\002 \001(\005\"9\n\rCandidate" +
      "Info\022\021\n\tnode_name\030\001 \001(\t\022\025\n\rrandom_number" +
      "\030\002 \001(\0052\350\001\n\013NodeService\022.\n\rAnnounceReady\022" +
      "\022.node.ReadyMessage\032\t.node.Ack\0220\n\016Announ" +
      "ceLeader\022\023.node.LeaderMessage\032\t.node.Ack" +
      "\0224\n\013RequestVote\022\021.node.VoteRequest\032\022.nod" +
      "e.VoteResponse\022A\n\025ExchangeCandidateInfo\022" +
      "\023.node.CandidateInfo\032\023.node.CandidateInf" +
      "oB\010\n\004nodeP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_node_ReadyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_node_ReadyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_ReadyMessage_descriptor,
        new java.lang.String[] { "NodeName", "State", });
    internal_static_node_Ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_node_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_Ack_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_node_LeaderMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_node_LeaderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_LeaderMessage_descriptor,
        new java.lang.String[] { "LeaderName", });
    internal_static_node_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_node_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_VoteRequest_descriptor,
        new java.lang.String[] { "CandidateName", "Term", "CandidateRandom", });
    internal_static_node_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_node_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_VoteResponse_descriptor,
        new java.lang.String[] { "VoteGranted", "Term", });
    internal_static_node_CandidateInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_node_CandidateInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_node_CandidateInfo_descriptor,
        new java.lang.String[] { "NodeName", "RandomNumber", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
