// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:node.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidate_name = 1;</code>
   * @return The candidateName.
   */
  java.lang.String getCandidateName();
  /**
   * <code>string candidate_name = 1;</code>
   * @return The bytes for candidateName.
   */
  com.google.protobuf.ByteString
      getCandidateNameBytes();

  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  int getTerm();

  /**
   * <code>int32 candidate_random = 3;</code>
   * @return The candidateRandom.
   */
  int getCandidateRandom();
}
