// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

/**
 * Protobuf type {@code node.VoteRequest}
 */
public final class VoteRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:node.VoteRequest)
    VoteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      VoteRequest.class.getName());
  }
  // Use VoteRequest.newBuilder() to construct.
  private VoteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VoteRequest() {
    candidateName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return node.Node.internal_static_node_VoteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return node.Node.internal_static_node_VoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            node.VoteRequest.class, node.VoteRequest.Builder.class);
  }

  public static final int CANDIDATE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidateName_ = "";
  /**
   * <code>string candidate_name = 1;</code>
   * @return The candidateName.
   */
  @java.lang.Override
  public java.lang.String getCandidateName() {
    java.lang.Object ref = candidateName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateName_ = s;
      return s;
    }
  }
  /**
   * <code>string candidate_name = 1;</code>
   * @return The bytes for candidateName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateNameBytes() {
    java.lang.Object ref = candidateName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private int term_ = 0;
  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  @java.lang.Override
  public int getTerm() {
    return term_;
  }

  public static final int CANDIDATE_RANDOM_FIELD_NUMBER = 3;
  private int candidateRandom_ = 0;
  /**
   * <code>int32 candidate_random = 3;</code>
   * @return The candidateRandom.
   */
  @java.lang.Override
  public int getCandidateRandom() {
    return candidateRandom_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidateName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, candidateName_);
    }
    if (term_ != 0) {
      output.writeInt32(2, term_);
    }
    if (candidateRandom_ != 0) {
      output.writeInt32(3, candidateRandom_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidateName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, candidateName_);
    }
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, term_);
    }
    if (candidateRandom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, candidateRandom_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof node.VoteRequest)) {
      return super.equals(obj);
    }
    node.VoteRequest other = (node.VoteRequest) obj;

    if (!getCandidateName()
        .equals(other.getCandidateName())) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (getCandidateRandom()
        != other.getCandidateRandom()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANDIDATE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateName().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + CANDIDATE_RANDOM_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateRandom();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static node.VoteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static node.VoteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static node.VoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static node.VoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static node.VoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static node.VoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static node.VoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static node.VoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static node.VoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static node.VoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static node.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static node.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(node.VoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code node.VoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:node.VoteRequest)
      node.VoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return node.Node.internal_static_node_VoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return node.Node.internal_static_node_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              node.VoteRequest.class, node.VoteRequest.Builder.class);
    }

    // Construct using node.VoteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candidateName_ = "";
      term_ = 0;
      candidateRandom_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return node.Node.internal_static_node_VoteRequest_descriptor;
    }

    @java.lang.Override
    public node.VoteRequest getDefaultInstanceForType() {
      return node.VoteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public node.VoteRequest build() {
      node.VoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public node.VoteRequest buildPartial() {
      node.VoteRequest result = new node.VoteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(node.VoteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candidateName_ = candidateName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.candidateRandom_ = candidateRandom_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof node.VoteRequest) {
        return mergeFrom((node.VoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(node.VoteRequest other) {
      if (other == node.VoteRequest.getDefaultInstance()) return this;
      if (!other.getCandidateName().isEmpty()) {
        candidateName_ = other.candidateName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (other.getCandidateRandom() != 0) {
        setCandidateRandom(other.getCandidateRandom());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              candidateName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              term_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              candidateRandom_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object candidateName_ = "";
    /**
     * <code>string candidate_name = 1;</code>
     * @return The candidateName.
     */
    public java.lang.String getCandidateName() {
      java.lang.Object ref = candidateName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @return The bytes for candidateName.
     */
    public com.google.protobuf.ByteString
        getCandidateNameBytes() {
      java.lang.Object ref = candidateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @param value The candidateName to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateName() {
      candidateName_ = getDefaultInstance().getCandidateName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @param value The bytes for candidateName to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int term_ ;
    /**
     * <code>int32 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }
    /**
     * <code>int32 term = 2;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(int value) {

      term_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 term = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      term_ = 0;
      onChanged();
      return this;
    }

    private int candidateRandom_ ;
    /**
     * <code>int32 candidate_random = 3;</code>
     * @return The candidateRandom.
     */
    @java.lang.Override
    public int getCandidateRandom() {
      return candidateRandom_;
    }
    /**
     * <code>int32 candidate_random = 3;</code>
     * @param value The candidateRandom to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateRandom(int value) {

      candidateRandom_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candidate_random = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateRandom() {
      bitField0_ = (bitField0_ & ~0x00000004);
      candidateRandom_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:node.VoteRequest)
  }

  // @@protoc_insertion_point(class_scope:node.VoteRequest)
  private static final node.VoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new node.VoteRequest();
  }

  public static node.VoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
    @java.lang.Override
    public VoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public node.VoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

