// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/consensus.proto
// Protobuf Java Version: 4.29.3

package consensus;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:consensus.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
