// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/consensus.proto
// Protobuf Java Version: 4.29.3

package consensus;

public final class Consensus {
  private Consensus() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Consensus.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consensus_LeaderMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_consensus_LeaderMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consensus_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_consensus_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consensus_PrivateKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_consensus_PrivateKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consensus_PrivateKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_consensus_PrivateKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consensus_VoteReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_consensus_VoteReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=src/main/java/org/parsa/grpcservicenod" +
      "e/proto/consensus.proto\022\tconsensus\"$\n\rLe" +
      "aderMessage\022\023\n\013leader_name\030\001 \001(\t\"\026\n\003Ack\022" +
      "\017\n\007success\030\001 \001(\010\"$\n\021PrivateKeyRequest\022\017\n" +
      "\007node_id\030\001 \001(\t\")\n\022PrivateKeyResponse\022\023\n\013" +
      "private_key\030\001 \001(\t\"<\n\nVoteReport\022\r\n\005voter" +
      "\030\001 \001(\t\022\021\n\tcandidate\030\002 \001(\t\022\014\n\004term\030\003 \001(\0052" +
      "\324\001\n\024CoreConsensusService\0228\n\014ReportLeader" +
      "\022\030.consensus.LeaderMessage\032\016.consensus.A" +
      "ck\022M\n\016SendPrivateKey\022\034.consensus.Private" +
      "KeyRequest\032\035.consensus.PrivateKeyRespons" +
      "e\0223\n\nReportVote\022\025.consensus.VoteReport\032\016" +
      ".consensus.AckB.\n\tconsensusP\001Z\037CoreBased" +
      "GoLang/proto;consensusb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_consensus_LeaderMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_consensus_LeaderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_consensus_LeaderMessage_descriptor,
        new java.lang.String[] { "LeaderName", });
    internal_static_consensus_Ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_consensus_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_consensus_Ack_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_consensus_PrivateKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_consensus_PrivateKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_consensus_PrivateKeyRequest_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_consensus_PrivateKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_consensus_PrivateKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_consensus_PrivateKeyResponse_descriptor,
        new java.lang.String[] { "PrivateKey", });
    internal_static_consensus_VoteReport_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_consensus_VoteReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_consensus_VoteReport_descriptor,
        new java.lang.String[] { "Voter", "Candidate", "Term", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
