// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/consensus.proto
// Protobuf Java Version: 4.29.3

package consensus;

public interface PrivateKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:consensus.PrivateKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
