// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/consensus.proto
// Protobuf Java Version: 4.29.3

package consensus;

/**
 * <pre>
 * پیام گزارش رأی از Node به Core
 * </pre>
 *
 * Protobuf type {@code consensus.VoteReport}
 */
public final class VoteReport extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:consensus.VoteReport)
    VoteReportOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      VoteReport.class.getName());
  }
  // Use VoteReport.newBuilder() to construct.
  private VoteReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VoteReport() {
    voter_ = "";
    candidate_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return consensus.Consensus.internal_static_consensus_VoteReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return consensus.Consensus.internal_static_consensus_VoteReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            consensus.VoteReport.class, consensus.VoteReport.Builder.class);
  }

  public static final int VOTER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object voter_ = "";
  /**
   * <pre>
   * نام نودی که رأی داده
   * </pre>
   *
   * <code>string voter = 1;</code>
   * @return The voter.
   */
  @java.lang.Override
  public java.lang.String getVoter() {
    java.lang.Object ref = voter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voter_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * نام نودی که رأی داده
   * </pre>
   *
   * <code>string voter = 1;</code>
   * @return The bytes for voter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVoterBytes() {
    java.lang.Object ref = voter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidate_ = "";
  /**
   * <pre>
   * نام نودی که رأی گرفته
   * </pre>
   *
   * <code>string candidate = 2;</code>
   * @return The candidate.
   */
  @java.lang.Override
  public java.lang.String getCandidate() {
    java.lang.Object ref = candidate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * نام نودی که رأی گرفته
   * </pre>
   *
   * <code>string candidate = 2;</code>
   * @return The bytes for candidate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateBytes() {
    java.lang.Object ref = candidate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 3;
  private int term_ = 0;
  /**
   * <pre>
   * شماره ترم
   * </pre>
   *
   * <code>int32 term = 3;</code>
   * @return The term.
   */
  @java.lang.Override
  public int getTerm() {
    return term_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(voter_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, voter_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, candidate_);
    }
    if (term_ != 0) {
      output.writeInt32(3, term_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(voter_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, voter_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(candidate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, candidate_);
    }
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, term_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof consensus.VoteReport)) {
      return super.equals(obj);
    }
    consensus.VoteReport other = (consensus.VoteReport) obj;

    if (!getVoter()
        .equals(other.getVoter())) return false;
    if (!getCandidate()
        .equals(other.getCandidate())) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VOTER_FIELD_NUMBER;
    hash = (53 * hash) + getVoter().hashCode();
    hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCandidate().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static consensus.VoteReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static consensus.VoteReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static consensus.VoteReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static consensus.VoteReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static consensus.VoteReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static consensus.VoteReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static consensus.VoteReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static consensus.VoteReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static consensus.VoteReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static consensus.VoteReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static consensus.VoteReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static consensus.VoteReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(consensus.VoteReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * پیام گزارش رأی از Node به Core
   * </pre>
   *
   * Protobuf type {@code consensus.VoteReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:consensus.VoteReport)
      consensus.VoteReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return consensus.Consensus.internal_static_consensus_VoteReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return consensus.Consensus.internal_static_consensus_VoteReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              consensus.VoteReport.class, consensus.VoteReport.Builder.class);
    }

    // Construct using consensus.VoteReport.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      voter_ = "";
      candidate_ = "";
      term_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return consensus.Consensus.internal_static_consensus_VoteReport_descriptor;
    }

    @java.lang.Override
    public consensus.VoteReport getDefaultInstanceForType() {
      return consensus.VoteReport.getDefaultInstance();
    }

    @java.lang.Override
    public consensus.VoteReport build() {
      consensus.VoteReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public consensus.VoteReport buildPartial() {
      consensus.VoteReport result = new consensus.VoteReport(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(consensus.VoteReport result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.voter_ = voter_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.candidate_ = candidate_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.term_ = term_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof consensus.VoteReport) {
        return mergeFrom((consensus.VoteReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(consensus.VoteReport other) {
      if (other == consensus.VoteReport.getDefaultInstance()) return this;
      if (!other.getVoter().isEmpty()) {
        voter_ = other.voter_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCandidate().isEmpty()) {
        candidate_ = other.candidate_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              voter_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              candidate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              term_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object voter_ = "";
    /**
     * <pre>
     * نام نودی که رأی داده
     * </pre>
     *
     * <code>string voter = 1;</code>
     * @return The voter.
     */
    public java.lang.String getVoter() {
      java.lang.Object ref = voter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * نام نودی که رأی داده
     * </pre>
     *
     * <code>string voter = 1;</code>
     * @return The bytes for voter.
     */
    public com.google.protobuf.ByteString
        getVoterBytes() {
      java.lang.Object ref = voter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * نام نودی که رأی داده
     * </pre>
     *
     * <code>string voter = 1;</code>
     * @param value The voter to set.
     * @return This builder for chaining.
     */
    public Builder setVoter(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      voter_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * نام نودی که رأی داده
     * </pre>
     *
     * <code>string voter = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoter() {
      voter_ = getDefaultInstance().getVoter();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * نام نودی که رأی داده
     * </pre>
     *
     * <code>string voter = 1;</code>
     * @param value The bytes for voter to set.
     * @return This builder for chaining.
     */
    public Builder setVoterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      voter_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object candidate_ = "";
    /**
     * <pre>
     * نام نودی که رأی گرفته
     * </pre>
     *
     * <code>string candidate = 2;</code>
     * @return The candidate.
     */
    public java.lang.String getCandidate() {
      java.lang.Object ref = candidate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * نام نودی که رأی گرفته
     * </pre>
     *
     * <code>string candidate = 2;</code>
     * @return The bytes for candidate.
     */
    public com.google.protobuf.ByteString
        getCandidateBytes() {
      java.lang.Object ref = candidate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * نام نودی که رأی گرفته
     * </pre>
     *
     * <code>string candidate = 2;</code>
     * @param value The candidate to set.
     * @return This builder for chaining.
     */
    public Builder setCandidate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * نام نودی که رأی گرفته
     * </pre>
     *
     * <code>string candidate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidate() {
      candidate_ = getDefaultInstance().getCandidate();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * نام نودی که رأی گرفته
     * </pre>
     *
     * <code>string candidate = 2;</code>
     * @param value The bytes for candidate to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int term_ ;
    /**
     * <pre>
     * شماره ترم
     * </pre>
     *
     * <code>int32 term = 3;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }
    /**
     * <pre>
     * شماره ترم
     * </pre>
     *
     * <code>int32 term = 3;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(int value) {

      term_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * شماره ترم
     * </pre>
     *
     * <code>int32 term = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000004);
      term_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:consensus.VoteReport)
  }

  // @@protoc_insertion_point(class_scope:consensus.VoteReport)
  private static final consensus.VoteReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new consensus.VoteReport();
  }

  public static consensus.VoteReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteReport>
      PARSER = new com.google.protobuf.AbstractParser<VoteReport>() {
    @java.lang.Override
    public VoteReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoteReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public consensus.VoteReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

