// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/broadcast.proto
// Protobuf Java Version: 4.29.3

package org.parsa.grpcservicenode.proto;

public final class Broadcast {
  private Broadcast() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Broadcast.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broadcast_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_broadcast_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broadcast_BroadcastMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_broadcast_BroadcastMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=src/main/java/org/parsa/grpcservicenod" +
      "e/proto/broadcast.proto\022\tbroadcast\"#\n\020Su" +
      "bscribeRequest\022\017\n\007node_id\030\001 \001(\t\"3\n\020Broad" +
      "castMessage\022\014\n\004hash\030\001 \001(\t\022\021\n\ttimestamp\030\002" +
      " \001(\t2[\n\020BroadcastService\022G\n\tSubscribe\022\033." +
      "broadcast.SubscribeRequest\032\033.broadcast.B" +
      "roadcastMessage0\001BD\n\037org.parsa.grpcservi" +
      "cenode.protoP\001Z\037CoreBasedGoLang/proto;br" +
      "oadcastb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_broadcast_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_broadcast_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_broadcast_SubscribeRequest_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_broadcast_BroadcastMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_broadcast_BroadcastMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_broadcast_BroadcastMessage_descriptor,
        new java.lang.String[] { "Hash", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
