// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/privateKey.proto
// Protobuf Java Version: 4.29.3

package org.parsa.grpcservicenode.privateKey;

public interface PrivateKeyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:privatekey.PrivateKeyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string private_key = 1;</code>
   * @return The privateKey.
   */
  java.lang.String getPrivateKey();
  /**
   * <code>string private_key = 1;</code>
   * @return The bytes for privateKey.
   */
  com.google.protobuf.ByteString
      getPrivateKeyBytes();
}
