// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/consensus.proto
// Protobuf Java Version: 4.29.3

package consensus;

public interface VoteReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:consensus.VoteReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * نام نودی که رأی داده
   * </pre>
   *
   * <code>string voter = 1;</code>
   * @return The voter.
   */
  java.lang.String getVoter();
  /**
   * <pre>
   * نام نودی که رأی داده
   * </pre>
   *
   * <code>string voter = 1;</code>
   * @return The bytes for voter.
   */
  com.google.protobuf.ByteString
      getVoterBytes();

  /**
   * <pre>
   * نام نودی که رأی گرفته
   * </pre>
   *
   * <code>string candidate = 2;</code>
   * @return The candidate.
   */
  java.lang.String getCandidate();
  /**
   * <pre>
   * نام نودی که رأی گرفته
   * </pre>
   *
   * <code>string candidate = 2;</code>
   * @return The bytes for candidate.
   */
  com.google.protobuf.ByteString
      getCandidateBytes();

  /**
   * <pre>
   * شماره ترم
   * </pre>
   *
   * <code>int32 term = 3;</code>
   * @return The term.
   */
  int getTerm();
}
