// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/broadcast.proto
// Protobuf Java Version: 4.29.3

package org.parsa.grpcservicenode.proto;

public interface BroadcastMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broadcast.BroadcastMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * هش یا متن رمز شده (هرچه Core بفرستد)
   * </pre>
   *
   * <code>string hash = 1;</code>
   * @return The hash.
   */
  java.lang.String getHash();
  /**
   * <pre>
   * هش یا متن رمز شده (هرچه Core بفرستد)
   * </pre>
   *
   * <code>string hash = 1;</code>
   * @return The bytes for hash.
   */
  com.google.protobuf.ByteString
      getHashBytes();

  /**
   * <pre>
   * زمان ارسال
   * </pre>
   *
   * <code>string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * زمان ارسال
   * </pre>
   *
   * <code>string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
