// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/broadcast.proto
// Protobuf Java Version: 4.29.3

package org.parsa.grpcservicenode.proto;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broadcast.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * شناسه Node
   * </pre>
   *
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <pre>
   * شناسه Node
   * </pre>
   *
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
