// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: CoreBasedGoLang/privateKey/privatekey.proto

package privatekey

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivateKeyService_ReceivePrivateKey_FullMethodName = "/privatekey.PrivateKeyService/ReceivePrivateKey"
)

// PrivateKeyServiceClient is the client API for PrivateKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivateKeyServiceClient interface {
	ReceivePrivateKey(ctx context.Context, in *PrivateKeyMessage, opts ...grpc.CallOption) (*Ack, error)
}

type privateKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateKeyServiceClient(cc grpc.ClientConnInterface) PrivateKeyServiceClient {
	return &privateKeyServiceClient{cc}
}

func (c *privateKeyServiceClient) ReceivePrivateKey(ctx context.Context, in *PrivateKeyMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PrivateKeyService_ReceivePrivateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateKeyServiceServer is the server API for PrivateKeyService service.
// All implementations must embed UnimplementedPrivateKeyServiceServer
// for forward compatibility.
type PrivateKeyServiceServer interface {
	ReceivePrivateKey(context.Context, *PrivateKeyMessage) (*Ack, error)
	mustEmbedUnimplementedPrivateKeyServiceServer()
}

// UnimplementedPrivateKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivateKeyServiceServer struct{}

func (UnimplementedPrivateKeyServiceServer) ReceivePrivateKey(context.Context, *PrivateKeyMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceivePrivateKey not implemented")
}
func (UnimplementedPrivateKeyServiceServer) mustEmbedUnimplementedPrivateKeyServiceServer() {}
func (UnimplementedPrivateKeyServiceServer) testEmbeddedByValue()                           {}

// UnsafePrivateKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivateKeyServiceServer will
// result in compilation errors.
type UnsafePrivateKeyServiceServer interface {
	mustEmbedUnimplementedPrivateKeyServiceServer()
}

func RegisterPrivateKeyServiceServer(s grpc.ServiceRegistrar, srv PrivateKeyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivateKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivateKeyService_ServiceDesc, srv)
}

func _PrivateKeyService_ReceivePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateKeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateKeyServiceServer).ReceivePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateKeyService_ReceivePrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateKeyServiceServer).ReceivePrivateKey(ctx, req.(*PrivateKeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivateKeyService_ServiceDesc is the grpc.ServiceDesc for PrivateKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivateKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privatekey.PrivateKeyService",
	HandlerType: (*PrivateKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceivePrivateKey",
			Handler:    _PrivateKeyService_ReceivePrivateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CoreBasedGoLang/privateKey/privatekey.proto",
}
