// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: CoreBasedGoLang/consensus/consensus.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderName    string                 `protobuf:"bytes,1,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderMessage) Reset() {
	*x = LeaderMessage{}
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderMessage) ProtoMessage() {}

func (x *LeaderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderMessage.ProtoReflect.Descriptor instead.
func (*LeaderMessage) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderMessage) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PrivateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKeyRequest) Reset() {
	*x = PrivateKeyRequest{}
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKeyRequest) ProtoMessage() {}

func (x *PrivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKeyRequest.ProtoReflect.Descriptor instead.
func (*PrivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *PrivateKeyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PrivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKeyResponse) Reset() {
	*x = PrivateKeyResponse{}
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKeyResponse) ProtoMessage() {}

func (x *PrivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKeyResponse.ProtoReflect.Descriptor instead.
func (*PrivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *PrivateKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

// پیام گزارش رأی جدید
type VoteReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voter         string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`         // اسم نود رأی‌دهنده
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"` // اسم کاندیدای رأی‌گرفته
	Term          int32                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`          // شماره term (یا همون دور انتخابات)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteReport) Reset() {
	*x = VoteReport{}
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReport) ProtoMessage() {}

func (x *VoteReport) ProtoReflect() protoreflect.Message {
	mi := &file_CoreBasedGoLang_consensus_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReport.ProtoReflect.Descriptor instead.
func (*VoteReport) Descriptor() ([]byte, []int) {
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *VoteReport) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *VoteReport) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *VoteReport) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_CoreBasedGoLang_consensus_consensus_proto protoreflect.FileDescriptor

const file_CoreBasedGoLang_consensus_consensus_proto_rawDesc = "" +
	"\n" +
	")CoreBasedGoLang/consensus/consensus.proto\x12\tconsensus\"0\n" +
	"\rLeaderMessage\x12\x1f\n" +
	"\vleader_name\x18\x01 \x01(\tR\n" +
	"leaderName\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11PrivateKeyRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"5\n" +
	"\x12PrivateKeyResponse\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\"T\n" +
	"\n" +
	"VoteReport\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x05R\x04term2\xd4\x01\n" +
	"\x14CoreConsensusService\x128\n" +
	"\fReportLeader\x12\x18.consensus.LeaderMessage\x1a\x0e.consensus.Ack\x12M\n" +
	"\x0eSendPrivateKey\x12\x1c.consensus.PrivateKeyRequest\x1a\x1d.consensus.PrivateKeyResponse\x123\n" +
	"\n" +
	"ReportVote\x12\x15.consensus.VoteReport\x1a\x0e.consensus.AckB2\n" +
	"\tconsensusP\x01Z#CoreBasedGoLang/consensus;consensusb\x06proto3"

var (
	file_CoreBasedGoLang_consensus_consensus_proto_rawDescOnce sync.Once
	file_CoreBasedGoLang_consensus_consensus_proto_rawDescData []byte
)

func file_CoreBasedGoLang_consensus_consensus_proto_rawDescGZIP() []byte {
	file_CoreBasedGoLang_consensus_consensus_proto_rawDescOnce.Do(func() {
		file_CoreBasedGoLang_consensus_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CoreBasedGoLang_consensus_consensus_proto_rawDesc), len(file_CoreBasedGoLang_consensus_consensus_proto_rawDesc)))
	})
	return file_CoreBasedGoLang_consensus_consensus_proto_rawDescData
}

var file_CoreBasedGoLang_consensus_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_CoreBasedGoLang_consensus_consensus_proto_goTypes = []any{
	(*LeaderMessage)(nil),      // 0: consensus.LeaderMessage
	(*Ack)(nil),                // 1: consensus.Ack
	(*PrivateKeyRequest)(nil),  // 2: consensus.PrivateKeyRequest
	(*PrivateKeyResponse)(nil), // 3: consensus.PrivateKeyResponse
	(*VoteReport)(nil),         // 4: consensus.VoteReport
}
var file_CoreBasedGoLang_consensus_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.CoreConsensusService.ReportLeader:input_type -> consensus.LeaderMessage
	2, // 1: consensus.CoreConsensusService.SendPrivateKey:input_type -> consensus.PrivateKeyRequest
	4, // 2: consensus.CoreConsensusService.ReportVote:input_type -> consensus.VoteReport
	1, // 3: consensus.CoreConsensusService.ReportLeader:output_type -> consensus.Ack
	3, // 4: consensus.CoreConsensusService.SendPrivateKey:output_type -> consensus.PrivateKeyResponse
	1, // 5: consensus.CoreConsensusService.ReportVote:output_type -> consensus.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CoreBasedGoLang_consensus_consensus_proto_init() }
func file_CoreBasedGoLang_consensus_consensus_proto_init() {
	if File_CoreBasedGoLang_consensus_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CoreBasedGoLang_consensus_consensus_proto_rawDesc), len(file_CoreBasedGoLang_consensus_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CoreBasedGoLang_consensus_consensus_proto_goTypes,
		DependencyIndexes: file_CoreBasedGoLang_consensus_consensus_proto_depIdxs,
		MessageInfos:      file_CoreBasedGoLang_consensus_consensus_proto_msgTypes,
	}.Build()
	File_CoreBasedGoLang_consensus_consensus_proto = out.File
	file_CoreBasedGoLang_consensus_consensus_proto_goTypes = nil
	file_CoreBasedGoLang_consensus_consensus_proto_depIdxs = nil
}
