// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:node.Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string leader_name = 1;</code>
   * @return The leaderName.
   */
  java.lang.String getLeaderName();
  /**
   * <code>string leader_name = 1;</code>
   * @return The bytes for leaderName.
   */
  com.google.protobuf.ByteString
      getLeaderNameBytes();

  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  int getTerm();
}
