// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

public interface ReadyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:node.ReadyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_name = 1;</code>
   * @return The nodeName.
   */
  java.lang.String getNodeName();
  /**
   * <code>string node_name = 1;</code>
   * @return The bytes for nodeName.
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();

  /**
   * <code>string state = 2;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 2;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
