// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/parsa/grpcservicenode/proto/node.proto
// Protobuf Java Version: 4.29.3

package node;

public interface VoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:node.VoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool vote_granted = 1;</code>
   * @return The voteGranted.
   */
  boolean getVoteGranted();

  /**
   * <code>int32 term = 2;</code>
   * @return The term.
   */
  int getTerm();
}
